# -*- coding: utf-8 -*-
"""Akhilesh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5i_CBwGqSXLfegGfuZlCucjyAgnoD0h
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
from sklearn.cluster import KMeans

uploaded=files.upload()
data=pd.read_csv("station_day.csv")

data

data=data.loc[data.StationId=='DL005']

data

data.describe()

data=data.drop(['Xylene'],axis=1)

data['Benzene'].fillna(value=data['Benzene'].mean(),inplace=True)

data.dropna()

x =data[['PM10','NO','SO2','O3']]
plt.hist(x, bins =20)
plt.show()

data.loc[:,['PM10','NO2','SO2','O3','AQI']].iloc[10:20,:]

X_train, X_test, y_train, y_test = train_test_split(data, y, test_size=0.2)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

