# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLaquX44cwqRc5jTGylYyCDh-ge-xn7S
"""

import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

df = pd.read_csv('station_day.csv')

print(df.info())

df1 = df.loc[df.StationId == "DL005"]
print(df1.head())

print("Fraction of observations have missing values:\n",(df1.isnull().sum())/len(df1))

#Handling missing value
df1.fillna(0)

data1 = df1[['PM10','NO2','SO2','O3','AQI']]
data1.hist()

df1.loc[:,['PM10','NO2','SO2','O3','AQI']].iloc[10:20,:]