# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4Lnijpo-Ybx1bZzIvY7-kXKlt1U3Bex
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd;
import numpy as np;
import matplotlib.pyplot as plt;
from sklearn.cluster import KMeans

df=pd.read_csv("station_day.csv");
df

df=df.loc[df.StationId=='DL005']
df

df.describe()

print("Fraction of observations have missing values:\n",(df.isnull().sum())/len(df))

#handling missing value
df.fillna(0)

df=df[['PM10','NO','SO2','O3']]
df.hist()

df.loc[:,['PM10','NO2','SO2','O3','AQI']].iloc[10:20,:]