# -*- coding: utf-8 -*-
"""Question1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lRnmr9PoNooczCUDGPMnH59CLUyR5qsj
"""

from google.colab import files
uploaded=files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

df = pd.read_csv('station_day.csv')
df.head()

df1=df.loc[df.StationId=="DL005"]
print(df1.head())

df1.describe()

print("Fraction of observation have values missing are :- \n",(df1.isnull().sum()/len(df1)))

data1=df[['PM10','NO2','SO2','O3','AQI']]
data1.hist()

df.loc[:,['PM10','NO2','SO2','O3','AQI']].iloc[10:20,:]

